### ISSUE TITLE
TypeError: Cannot supply flags when constructing one RegExp from another

### ISSUE THREAD

**Issue by MichaelPaulukonis** [MichaelPaulukonis/NaPoGenMo2016#10]
```
2016-07-13T16:01:49.392257+00:00 app[scheduler.1176]: TypeError: Cannot supply flags when constructing one RegExp from another
2016-07-13T16:01:49.392259+00:00 app[scheduler.1176]:     at new RegExp (native)
2016-07-13T16:01:49.389305+00:00 app[scheduler.1176]: seed: duubu0w
2016-07-13T16:01:49.392263+00:00 app[scheduler.1176]:     at teller [as poem] (/app/lib/poetifier.js:324:16)
2016-07-13T16:01:49.392261+00:00 app[scheduler.1176]:     at new ng (/app/lib/lrRunner.js:31:24)
2016-07-13T16:01:49.392264+00:00 app[scheduler.1176]:     at teller (/app/index.js:46:24)
2016-07-13T16:01:49.392262+00:00 app[scheduler.1176]:     at ng (/app/lib/lrRunner.js:8:12)
2016-07-13T16:01:49.392264+00:00 app[scheduler.1176]:     at Object.<anonymous> (/app/index.js:115:1)
2016-07-13T16:01:49.392265+00:00 app[scheduler.1176]:     at Module._compile (module.js:434:26)
2016-07-13T16:01:49.392262+00:00 app[scheduler.1176]:     at texts.filter (/app/lib/poetifier.js:283:46)
2016-07-13T16:01:49.392260+00:00 app[scheduler.1176]:     at stripPunct.filter.opts [as filter] (/app/lib/linereduce.js:58:22)
2016-07-13T16:01:49.392259+00:00 app[scheduler.1176]:     at Object.module.exports.search.options [as search] (/app/lib/linefind.js:33:24)
2016-07-13T16:01:50.311629+00:00 heroku[scheduler.1176]: Process exited with status 0
```

**Comment by MichaelPaulukonis** [comment]
I could not recreate the error in dev -- but I discovered that the node runtimes in my dev/test and heroku prod were different (node 6.1 in dev, and node 4.x on Heroku).

I updated the node version in `package,json`.
Additionally, I updated the regex processing code to better handling processing an existing regex.
