### ISSUE TITLE
titling: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by MichaelPaulukonis** [MichaelPaulukonis/NaPoGenMo2016#8]
```
λ index.js -l -s v3gs2rn.ynscq5mi
{
  "handlePunctuation": "noParen",
  "byNewlineOrPunctuation": "punctuation",
  "capitalize": {
    "method": "capitalizeAsCorpus",
    "customSentence": false,
    "customLine": false,
    "customI": false
  },
  "appendToPoem": "appendQuestion",
  "statusVerbosity": 0
}
nonnet
100
TypeError: Cannot read property 'concat' of undefined
    at getRelevantSentences (C:\projects\napogenmo2016\node_modules\in-a-nutshell\lib\in-a-nutshell.js:131:48)
    at Object.nutshell (C:\projects\napogenmo2016\node_modules\in-a-nutshell\lib\in-a-nutshell.js:29:26)
    at titleSummaryStrategy (C:\projects\napogenmo2016\lib\poetifier.js:200:24)
    at titlefier (C:\projects\napogenmo2016\lib\poetifier.js:180:12)
    at onePoem (C:\projects\napogenmo2016\lib\poetifier.js:293:24)
    at teller [as poem] (C:\projects\napogenmo2016\lib\poetifier.js:324:16)
    at teller (C:\projects\napogenmo2016\index.js:46:24)
    at Object.<anonymous> (C:\projects\napogenmo2016\index.js:115:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
..............................................
.........................................
...................................
..............................
.........................
....................
...............
..........
.....
```

well, that makes sense. There aren't any sentences, in a sense. Maybe.

**Comment by MichaelPaulukonis** [comment]
Sadly, this seed now generates text.

I suppose a way to test this would be a unit-test with a hard-coded "all punctuation" poem that attempts to titleify with the summarizer.

**Comment by MichaelPaulukonis** [comment]
This was a problem with the Summary method. Since there are no words, it errors out.
Now returns "[UNTITLED]" if summarize error.

TODO: the WordFreq method would probably fail on this, as well.

The failure-wrapper could extend around any of the methods, perhaps.

There's also the idea of some pre-processing, to pick an appropriate method if random selection [eg, not specific method requested], but have not implemented.

That would, however, be much more in-line with the idea of "strategies" - depending on the content and rules different types of titles have a greater chance of being selected.

**Comment by MichaelPaulukonis** [comment]
I think this has all been handled.
